# Generated by Django 4.1.1 on 2023-02-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_delete_cart_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
