# Generated by Django 4.1.1 on 2023-02-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_product_product_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('science', 'Science'), ('electrical', 'Electrical'), ('clothes', 'clothes'), ('watches', 'Watches'), ('handbag', 'Handbag')], default='science', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categories'),
        ),
    ]
